services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: aditya
      MYSQL_PASSWORD: aditya
      MYSQL_ROOT_PASSWORD: aditya